# Dict[PROMPT_LABEL: List[MASK_LABELS]]
labels = {
    "AGENTS_SING": ["AGENT_SING"],
    "AGENTS_PLUR": ["AGENT_PLUR"],
    "ADJ": ["ADJ"],
    "VERB_SING": ["VERB_SING"],
    "VERB_PLUR": ["VERB_PLUR"]
}

# Dict[PROMPT_LABEL: List[Prompts with 1 or more masks]]
prompts = {
        "AGENTS_SING": [
            "The <mask> is reading a book.",
            "The <mask> is working at the hospital.",
            "The <mask> is walking to school.",
            "The <mask> is writing software.",
            "The <mask> is teaching mathematics.",
            "The <mask> is repairing the engine.",
            "The <mask> is cooking dinner.",
            "The <mask> is managing the project.",
            "The <mask> is designing a bridge.",
            "The <mask> is delivering a lecture.",
            "The <mask> is studying late tonight.",
            "The <mask> is singing beautifully.",
            "The <mask> is driving the bus.",
            "The <mask> is painting a portrait.",
            "The <mask> is conducting an experiment.",
            "The <mask> is guarding the entrance.",
            "The <mask> is selling vegetables.",
            "The <mask> is healing the patient.",
            "The <mask> is cleaning the classroom.",
            "The <mask> is leading the investigation."
        ],
        "AGENTS_PLUR": [
            "The <mask> are reading books.",
            "The <mask> are working at the hospital.",
            "The <mask> are walking to school.",
            "The <mask> are writing software.",
            "The <mask> are teaching mathematics.",
            "The <mask> are repairing engines.",
            "The <mask> are cooking dinners.",
            "The <mask> are managing projects.",
            "The <mask> are designing bridges.",
            "The <mask> are delivering lectures.",
            "The <mask> are studying late tonight.",
            "The <mask> are singing beautifully.",
            "The <mask> are driving buses.",
            "The <mask> are painting portraits.",
            "The <mask> are conducting experiments.",
            "The <mask> are guarding the entrances.",
            "The <mask> are selling vegetables.",
            "The <mask> are healing patients.",
            "The <mask> are cleaning classrooms.",
            "The <mask> are leading investigations.",
            "The <mask> are standing outside.",
            "The <mask> are filing reports.",
            "The <mask> are drawing designs.",
            "The <mask> are giving presentations.",
            "The <mask> are attending classes.",
            "The <mask> are conducting interviews.",
            "The <mask> are playing instruments.",
            "The <mask> are analyzing data.",
            "The <mask> are monitoring the situation.",
            "The <mask> are preparing dinner."
        ],
        "ADJ": [
            "The very <mask> student passed the exam.",
            "The most <mask> employee got the promotion.",
            "A truly <mask> player scored the goal.",
            "An extremely <mask> scientist published the paper.",
            "A highly <mask> lawyer won the case.",
            "The remarkably <mask> nurse cared for the patient.",
            "A notably <mask> artist painted the portrait.",
            "An incredibly <mask> engineer designed the bridge.",
            "A consistently <mask> manager led the project.",
            "Their surprisingly <mask> approach worked.",
            "The design is exceptionally <mask> and innovative.",
            "This method is refreshingly <mask>.",
            "Their proposal was deliberately <mask> but effective.",
            "The report seemed unusually <mask>.",
            "The plan was especially <mask> to reviewers.",
            "Her style felt increasingly <mask>.",
            "The result looked particularly <mask>.",
            "His behavior remained disturbingly <mask>.",
            "The outcome stayed stubbornly <mask>.",
            "Their strategy was strikingly <mask>.",
            "The menu was enticingly <mask>.",
            "The solution proved remarkably <mask>.",
            "Her tone remained subtly <mask>.",
            "His method appeared reliably <mask>.",
            "The color felt strangely <mask>.",
            "The choice was clearly <mask> and well-reasoned.",
            "This answer was too <mask> for approval.",
            "That decision seemed dangerously <mask>.",
            "His idea proved surprisingly <mask>.",
            "Their performance was consistently <mask> and strong.",
            "The house looked undeniably <mask>.",
            "Their plan became more <mask> over time.",
            "This approach remained thoroughly <mask>.",
            "The machine operated surprisingly <mask>.",
            "Her expression was subtly <mask> throughout.",
            "The result felt uncomfortably <mask> to many.",
            "The document appeared deliberately <mask> in tone.",
            "Their strategy remained characteristically <mask>.",
            "The gesture was unmistakably <mask>.",
            "This finding is notably <mask>.",
            "Their actions stayed quite <mask> overall.",
            "The design was frustratingly <mask> at times.",
            "His comment was unnecessarily <mask> and harsh.",
            "Their work remained effortlessly <mask>.",
            "The interface feels intentionally <mask>.",
            "That remark was pointedly <mask> and critical.",
            "The condition stayed stubbornly <mask>.",
            "The outcome was predictably <mask>.",
            "Their answer seemed carefully <mask> chosen."
        ],
        "VERB_SING": [
            "The man is <mask> a book.",
            "The woman is <mask> at the hospital.",
            "The child is <mask> to school.",
            "The engineer is <mask> software.",
            "The teacher is <mask> mathematics.",
            "The mechanic is <mask> the engine.",
            "The chef is <mask> dinner.",
            "The manager is <mask> the project.",
            "The architect is <mask> a bridge.",
            "The professor is <mask> a lecture.",
            "The student is <mask> late tonight.",
            "The singer is <mask> beautifully.",
            "The driver is <mask> the bus.",
            "The artist is <mask> a portrait.",
            "The scientist is <mask> an experiment.",
            "The guard is <mask> the entrance.",
            "The vendor is <mask> vegetables.",
            "The doctor is <mask> the patient.",
            "The janitor is <mask> the classroom.",
            "The detective is <mask> the investigation.",
            "The team is <mask> outside."
        ],
        "VERB_PLUR": [
            "The men are <mask> books.",
            "The nurses are <mask> at the hospital.",
            "The children are <mask> to school.",
            "The programmers are <mask> software.",
            "The instructors are <mask> mathematics.",
            "The mechanics are <mask> engines.",
            "The cooks are <mask> dinners.",
            "The supervisors are <mask> projects.",
            "The designers are <mask> bridges.",
            "The lecturers are <mask> lectures.",
            "The students are <mask> late tonight.",
            "The singers are <mask> beautifully.",
            "The drivers are <mask> buses.",
            "The painters are <mask> portraits.",
            "The researchers are <mask> experiments.",
            "The guards are <mask> the entrances.",
            "The vendors are <mask> vegetables.",
            "The physicians are <mask> patients.",
            "The cleaners are <mask> classrooms.",
            "The investigators are <mask> investigations.",
            "The clerks are <mask> reports.",
            "The artists are <mask> designs.",
            "The speakers are <mask> presentations.",
            "The attendees are <mask> classes.",
            "The recruiters are <mask> interviews.",
            "The musicians are <mask> instruments.",
            "The analysts are <mask> data.",
            "The supervisors are <mask> the situation.",
            "The chefs are <mask> dinner."
        ],
}