from source.cfg import CFG
from source.utils import join

def generate_examples(grammar: CFG, num_examples: int = 20, print_tree: bool = False) -> None:
    """Prints examples generated by a grammar."""

    # Generate examples
    for _ in range(num_examples):

        # Generate a random tree
        tree = grammar.generate(False)

        # Get the terminal yield of the tree
        tokens = tree.output()

        # See the tree structure and the yield
        if print_tree:
            print("sampled tree:", tree) # Print the tree structure
            print("yield:", tokens) # Print the yield (list of tokens)
        
        # Otherwise print the examples
        else:
            text = join(tokens) # Join the tokens into a sentence
            print(text) # Print the resulting sentence
