from source.cfg import CFG
from source.utils import join

def generate_examples(grammar: CFG) -> None:
    """Prints examples generated by a grammar."""

    # Generate examples
    for _ in range(20):

        # Generate a random tree
        tree = grammar.generate(False)

        # # Print the tree structure
        # print("sampled tree:", tree)

        # Get the terminal yield of the tree
        tokens = tree.output()

        # # Print the yield (list of tokens)
        # print("yield:", tokens)

        # Join the tokens into a sentence
        text = join(tokens)

        # Print the resulting sentence
        print(text)
